language: objective-c
osx_image: xcode10.1

cache:
  bundler: true

bundler_args: --jobs 3 --retry 3

rvm:
  - 2.3.1

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

script: bundle exec rake
